### ISSUE TITLE
로그인 기능 구현

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#10]
### 1. 회원가입 기능 추가
- 보호자, 요양보호사 회원가입 기능 ( password 암호화 기능 )
- 각각 Role 부여

### 2. 로그인 기능 추가
- 로그인 url 컨트롤러 추가
- 스프링 시큐리티 + JWT 사용
- 어노테이션을 이용, 컨트롤러에서 권한 관리 (@Preauthorize )

[보호자로그인]
- api : v1/login?role=guardians
- request body : Id/password
- response header : auth token(jwt)

[요양보호사로그인]
- api : v1/login?role=careworkers
- 이하 동일

## ☑️ TODO

- [x] Spring Security 설정 (SecurityConfig 클래스를 만들어 WebSecurityConfigurerAdapter 또는 SecurityFilterChain을 사용하여 보안 설정을 관리)
- [x] 필터 구현
- [x] entity 비밀번호 field 추가
- [x] 회원가입 시 비밀번호 암호화 적용
- [x] 로그인 컨트롤러 추가 : response header 로 "authorization : token" 을 통해 stateless하게 관리
- [x] 회원가입 정상 동작 테스트
- [x] 로그인 정상 동작 테스트
- [ ] @Preauthorize 정상 동작 테스트
- [ ] 권한있는 상태에서의 접근 성공 테스트
- [ ] 권한없는 상태에서의 접근 차단 테스트

## 추후 진행하면 좋을 것들

- 토큰 만료시간 갱신
- 로그아웃 기능
- 회원가입 시 JWT header에 넣어주기 (아마 이번에 해야할수도?)
- 보호자 kakao 연동 로그인?
