### ISSUE TITLE
스웨거 API 테스트

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#101]
## 📝 이슈 설명

 배포 전 [스웨거](http://localhost:8080/swagger-ui/index.html)를 통해 API 테스트해봅시다!!!!

```
관련 코드
```

## ☑️ TODO

1. `Admin API`
- [x] `[관리자] 서버관리자 (Admin)` - 서버관리자 정보 조회, 수정 
- [x] `[관리자] 요양원 (Institution)` -  요양원 정보 조회, 수정, 삭제 추가
- [x] `[관리자] 보호자 (Guardian)` - 보호자 정보 조회, 추가, 수정, 삭제
- [x] `[관리자] 요양보호사 관리` - 관리자가 요양사 정보를 조회, 수정, 추가, 삭제
- [x] `[관리자] 돌봄대상자 관리` - 관리자가 관리하는 모든 돌봄대상자 정보 조회, 추가, 수정 삭제

2. Auth API 
- [x] 로그인, 로그아웃 

3. Careworker API 
- [x] `[요양보호사] 돌봄대상자 관리`
- [x] `[요양보호사] 마이페이지`
- [x] `[요양보호사] 차트 관리`

4. Chart API
- [x] `[요양보호사] 차트 관리`
- [x] `[보호자] 차트 조회`

5. Excel API 
- [x] 엑셀 양식 다운로드 및 업로드 

6. Guardian API 
- [ ] [보호자]
- [ ] [보호자] 돌봄대상자 조회
- [ ] [보호자] 차트 조회

7. Institution API
- [ ] [요양원] 보호자 관리
- [ ] [요양원] 돌봄대상자 관리 
- [ ] [요양원] 요양보호사 관리 

8. 차트 요약 API (테스트용)
- [x] 요약 API
