### ISSUE TITLE
계층 분리, 테이블명을 제외하고 전부 단수형 처리, 간단한 리팩토링 작업

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#18]
## 📝 이슈 설명
- 9월 23일 월요일 회의에서 상의했던 대로 도메인별로 계층을 나누어 개발을 진행하기로 결정하였습니다!

## ☑️ TODO

- [x] 도메인 단위로 계층을 분리합니다.
- [x] 테이블명은 복수형, 나머지는 전부 단수형으로 바꾸기 
- [x] 간단한 리팩토링 작업
