### ISSUE TITLE
Week3 강철 멘토님 코드 리뷰 반영하기 

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#22]
## 📝 이슈 설명
 Week3 리뷰 내용을 반영하고 멘토님 리뷰에 reply를 답니다.
 추가적으로 궁금한 사항같은 경우 `Add a comment`를 통해 멘토님께 직접 여쭤보셔도 되고 톡방에서 저희끼리 상의해봐도 좋을 거 같아요!!
 [멘토님 리뷰 바로가기 ](https://github.com/kakao-tech-campus-2nd-step3/Team13_BE/pull/21#pullrequestreview-2322757188)

## ☑️ TODO

- [ ] 멘토님 리뷰 반영하기 
- [ ] 반영 후 reply 달기 
- [ ] 이슈 구현 후 PR 날리고 톡방에 알리기
