### ISSUE TITLE
[요양보호사 / 보호자] Line messaging API를 활용하여 알림 서비스 구현하기 

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#23]
## 📝 이슈 설명

 주기적으로 요양보호사 / 보호자에게 LINE 메시지를 보내는 API를 구현합니다.

### 1. 유저 플로우 (보호자)
(1) QR 코드 혹은 [친추 초대 URL](https://lin.ee/R3Rse0o)을 통해 Line 앱에 들어갑니다.
(2) 보호자가 친구 추가 버튼을 누르자마자 서버에서는 해당 사용자의 UserId를 토대로 보호자인지 요양보호사인지 Stranger인지 확인합니다. 
(3) 보호자임이 확인된다면 DB에 Line에서의 UserId를 저장하고 웰컴 메시지를 띄웁니다.
- UserId를 저장하는 이유는 추후에 해당 UserId를 토대로 서버에서 사용자에게 메시지를 보낼 수 있기 때문입니다. 
- 웰컴메시지의 내용은 다음과 같습니다.
```
 [보호자 이름] 보호자님, 안녕하세요! 🌸
 최고의 요양원 서비스 돌봄다리입니다. 🤗
 저희와 함께 해주셔서 정말 감사합니다! 🙏
 새롭게 작성된 차트 내용을 원하시는 시간에 맞춰 알려드릴 수 있어요. ⏰
 알림을 받고 싶은 시간을 알려주세요! 💬 예: 오후 9시
```
(4) 보호자가 채팅창에 알림을 받고 싶은 시간을 입력합니다.
- ex) 오전 9시
(5) 서버에서 해당 메시지를 받은 후 알림 받고 싶은 시간을 DB에 업데이트합니다.
(6) 매 분마다 돌아가는 스케쥴러를 이용하여 현재 시간에 알림을 받고 싶어하는 보호자가 있다면 알림을 보내게 됩니다.

### 2. 유저 플로우 (요양보호사)
(1) QR 코드 혹은 [친추 초대 URL](https://lin.ee/R3Rse0o)을 통해 Line 앱에 들어갑니다.
(2) 보호자가 친구 추가 버튼을 누르자마자 서버에서는 해당 사용자의 UserId를 토대로 보호자인지 요양보호사인지 Stranger인지 확인합니다. 
(3) 요양보호사임이 확인된다면 DB에 Line에서의 UserId를 저장하고 웰컴 메시지를 띄웁니다.
- UserId를 저장하는 이유는 추후에 해당 UserId를 토대로 서버에서 사용자에게 메시지를 보낼 수 있기 때문입니다. 
- 웰컴메시지의 내용은 다음과 같습니다.
```
 [보호자 이름] 요양보호사님, 안녕하세요! 🌸
 최고의 요양원 서비스 돌봄다리입니다. 🤗
 저희와 함께 해주셔서 정말 감사합니다! 🙏
 차트 작성 알림을 받고 싶은 시간을 알려주세요! 예: 오후 9시 💬
```
(4) 요양보호사가 채팅창에 알림을 받고 싶은 시간을 입력합니다.
- ex) 오전 9시
(5) 서버에서 해당 메시지를 받은 후 알림 받고 싶은 시간을 DB에 업데이트합니다.
(6) 매 분마다 돌아가는 스케쥴러를 이용하여 현재 시간에 알림을 받고 싶어하는 보호자가 있다면 알림을 보내게 됩니다.

### 3. 유저 플로우 (Stranger : 보호자도 요양보호사도 아닌 사람)
(1) QR 코드 혹은 [친추 초대 URL](https://lin.ee/R3Rse0o)을 통해 Line 앱에 들어갑니다.
(2) 보호자가 친구 추가 버튼을 누르자마자 서버에서는 해당 사용자의 UserId를 토대로 보호자인지 요양보호사인지 Stranger인지 확인합니다. 
(3) Stranger라면 아래와 같은 웰컴 메시지를 띄웁니다.
```
 [Stranger 이름]님, 안녕하세요!
 최고의 요양원 서비스 돌봄다리입니다. 🤗
 저희 서비스는 보호자와 요양보호사를 위한 서비스입니다.
 알림 기능을 이용하시려면 요양원을 통해 회원가입해주시기 바랍니다. 😅
```

---

## ☑️ TODO
- [x] Line Developers 가입 후 channel-token, channel-secret 가져오기
- [x] 의존성 추가 (Line-messaging-api 라이브러리)
- [x] configuration 설정 (channelToken값 추가해서)
- [x] follow event : 요양보호사/보호자가 라인 채널 친구 추가 시 웰컴 메시지 띄우기 
- [x] message event : 요양보호사/보호자가 채팅방에 알림 받고 싶어하는 시간대 입력하면 저장하기 
- [x] scheduler 구현 
- [x] ngrok 통해 로컬에서 테스트해보기
    - 로그인 후 테스트해야함 
- [x] 알림 시간은 30분 단위가 되어어야함 
- [x] 전체적인 리팩토링

**Comment by 20jcode** [comment]
1. 보호자 or 요양보호사 두 case 전부 회원가입 시 기본값으로 정해진 시간이 있으면 좋겠어요. 그리고 채팅보다는 웹페이지에서 자신의 알림정보를 수정할 수 있어야할 것 같아요 ( 시간 변경 or 카카오톡 <-> sms <-> 라인 등등 연락수단 변경 )

ex) 기본적으로 보호자는 매일 오후 9시 새로운 차트 업데이트가 있는 경우 알림을 받는다. -> 개인정보페이지에서 해당 시간 수정 가능

ex2) 요양보호사는 요양원에서 등록한 기본적인 알림 workflow를 기본값으로 세팅. 이후 개인정보페이지에서 해당 알림 CRUD 가능

2. 스케줄러가 매분 돌아가면? 서버측에 무리는 없는지 궁금합니다!

**Comment by pykido** [comment]
ㅇㅎㅇㅎ 그러면 기본값을 보호자는 매일 아침 10시, 요양보호사는 매일 오후 5시로 해두는게 어떤가유?
  그리고 스케쥴러의 경우 fastapi로 옛날에 1분마다 돌려봤을 때 딱히 무리는 없었는데 솔직히 요양보호사랑 보호자가 9시 5분 이렇게 설정 안하고 10분 단위, 30분 단위로 알림 시간을 정할 거 같아서 스케쥴러를 10분 혹은 30분마다 돌리는건 어떤가유?

**Comment by 20jcode** [comment]
1. 저는 Quartz 라이브러리로 하는 것이 괜찮아보이더라구요. 

기본적인 스프링 스케쥴러로는 복잡한 작업에 적합하지않다? 는 말도 있고, 단일 서버환경에서는 큰 문제가 없겠지만 만약 다중서버환경에서 해당 알림서비스를 운영해야한다면 더더욱 빡빡해질 것 같은...? 생각이 듭니다.

예를 들어, 선행조사한 케어* 서비스를 생각하면 약 1만개 이상의 요양서비스업체가 등록되어있는데,
그중 10% - 1000개의 기관만 저희서비스를 사용한다고 해도 서버확장은 필요할 것 같고 비용적인 측면에서는 scale out 전략을 취해야하지 않을까요... (어느정도에서 서버확장을 해야하는지 명확하게 판단내리기 어렵네요...ㅎㅎ;;)

만약 다중서버가 된다면... 알림에 대한 전략도 스케쥴러를 사용한다면 조금 많이 복잡해질 것 같습니다!! ( 근데 태윤님 생각에 무리없다 생각되시면 스케쥴러 사용해도 상관없을 듯 합니다! )



2. 시간단위는 30분 단위로 통일해도 괜찮을 것 같습니다. 현 서비스 기획 상으로는 긴급하거나 특정 시간에 무조건적인 알림이 보장되는 것이 아닌, 조금 널널하게 생각해도 된다고 봅니당.



3. 제 개인적인 의견이긴 한데, 오류로 인해 알림이 2번오는 경우는 절대 절대!! 없었으면 합니다...
해당 부분이 좀 불쾌감이 많이 느껴질 것 같아서요...

**Comment by pykido** [comment]
1. 일단은 저희 스케쥴링 로직 자체는 굉장히 간단한 작업을 수행합니다. 10분~1시간 간격으로 알림 보낼 사람들한테 보내기만 하니깐용! 그런데 Quartz같은 경우는 초기 설정이 다소 복잡하고 DB와도 연관되어있는 방식이라 추후에 스케쥴러 로직이 복잡해진다면 고려해보려고 하였습니당!
- 추가적으로 경미님이랑 영준님 모두 실제로 동작할 경우, 실제로 서비스를 배포할 경우를 생각해보았을 떄 서버의 안정성에 대해 되게 걱정이 많으시더군용!
- 그래서 제가 관련 자료도 많이 찾아보고 실제 서비스에서 이 부분을 어떻게 처리하는지 알아보니 해결점은 다음과 같았습니다.
- 서버를 여러 대 줘서 로드 밸런서를 통해 관리한다. (폐 1개로 숨을 쉬지 않고 2개로 쉬잖아욤? 그래서 폐 1개가 이상하더라도 숨을 쉴 수 있듯 서버 또한 하나가 죽더라도 다른 서버들이 동작할 수 있게끔 관리하는 방법입니다.)
- 더 나은 방법이 있다면 서로 공유하는 것도 좋을 거 같네욤! 저도 더 찾아보겠숩니당

2. 30분 단위 좋아욤~!

3. ㅇㅎㅇㅎ 오류로 인해 알림이 2번 오는 경우는 제가 자신 있게 해결할 수 있을 거 같아요. amazon의 sqs를 사용하면 보내야할 알림을 큐(queue)에 쌓게 됩니다. 그렇기에 서버가 죽거나 에러가 나더라도 큐(queue)에 처리되지 않은 알림이 쌓여있으니 명시적으로 알림을 관리할 수 있어서 해당 방법으로 해결하면 좋을 거 같아요. 물론 지금 프로젝트 자체가 너무 규모가 작기도 하고 어디까지 실제 서비스처럼 동작하게 만들어야할지는 같이 의논해봐야하니깐용!
