### ISSUE TITLE
LLM을 활용하여 돌봄대상자별 차트 요약하기 

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#35]
## 📝 이슈 설명

 요양보호사가 차트 작성 시 해당 차트 내용을 바탕으로 돌봄 대상자의 상태, 신체활동, 인지관리, 간호관리, 회복훈련 내용을 LLM을 활용하여 정리하여 저장할 수 있어야 합니다.

```
{
  "인지관리": "단어 암기 시간을 좀 더 늘리거나 집중력을 높이는 방법을 고민해볼 계획이다.",
  "신체활동": "처음에는 걷는 게 힘들었지만, 시간이 지날수록 괜찮아졌다. 앞으로는 산책을 좀 더 자주 해볼까 한다.",
  "기능회복훈련": "손의 기능을 회복하기 위해 훈련을 했고, 점차 나아지고 있다.",
  "상태": "피로감이 많이 줄어든 상태, 좋은 컨디션을 유지하고 있다.",
  "간호관리": "약을 꾸준히 복용 중이고 큰 문제는 없다."
}
```

## ☑️ TODO

- [x] json형식으로 openAi가 대답할 수 있도록 파인튜닝하기
- [x] 저장된 차트와 연결해서 1일치를 가져와 요약하는 서비스 만들기
- [x] 요약한 내용을 db에 저장하기
- [x] controller만들기
