### ISSUE TITLE
RDS - 공용 DB 연결하기 

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#5]
## 📝 이슈 설명

이슈 설명을 작성하세요.
- 돌봄다리 공용 DB 만들기

## ☑️ TODO
- [x] RDS로 DB 배포하기  
- [x] build.gradle : MySQL 의존성 추가
- [x] application.yml : AWS RDS 데이터베이스 연결 정보를 포함. 
- [x] 엔티티 생성 테스트 
- [x] 설정 파일 재정렬
