### ISSUE TITLE
Week 6 리뷰 반영하기

### ISSUE THREAD

**Issue by 20jcode** [kakao-tech-campus-2nd-step3/Team13_BE#55]
## 📝 이슈 설명

리뷰 반영을 위한 문서입니다.

## ☑️ TODO

- [ ] password 일치 부분 분리
- [ ] Repository 중복 검사 : ensureUnique ~~~ 문법으로 통일
- [ ] excelController 수정하기
- [ ] 엑셀 업로드 시 validation 구문 추가
- [ ] 엑셀 업로드 시 DTO를 도메인마다 구분해주기
- [ ] 엑셀 다운로드 서비스 중복 제거해보기
