### ISSUE TITLE
[차트 입력 기능] OCR + S3 + presigned url로 구현하기

### ISSUE THREAD

**Issue by pykido** [kakao-tech-campus-2nd-step3/Team13_BE#81]
## 📝 이슈 설명
1. 프론트엔드에서 이미지 업로드
- 프론트엔드에서는 사용자 이미지를 S3에 직접 업로드할 수 있도록 Presigned URL을 요청한다.
2. Presigned URL 생성
- 백엔드에서 S3 Presigned URL을 생성하고 이를 프론트엔드에 반환한다.
- 이 URL을 통해 사용자는 인증 없이도 S3에 이미지를 업로드할 수 있습니다.
3. 이미지 업로드 및 저장된 URL을 DB에 저장하기
<img width="654" alt="스크린샷 2024-11-08 오후 3 03 48" src="https://github.com/user-attachments/assets/43a1f5c1-f748-4053-89df-2eaf5d443ef9">

- 프론트엔드는 Presigned URL을 사용해 S3에 이미지를 업로드한 후 이미지가 저장된 URL을 반환 받는다. 
- DB에 이미지가 저장된 URL을 저장한다.
4. 백엔드에서 클로바 OCR 요청
- DB에 저장된 이미지 URL을 바탕으로 네이버 클로바 OCR API로 요청을 보낸다.
- 이때, 클로바 OCR API의 엔드포인트에 이미지의 URL 또는 Base64 인코딩을 사용해 전달할 수 있다.
5. OCR 결과 반환
- 네이버 클로바 OCR에서 반환된 텍스트 결과를 백엔드에서 가공하여 프론트엔드로 응답합니다.

## ☑️ TODO

- [x] AWS에서 S3 설정하기 
    - [참고 블로그 1 ](https://velog.io/@penrose_15/Spring-Boot%EC%97%90%EC%84%9C-S3-Presigned-URL-%EC%83%9D%EC%84%B1-%EB%B0%A9%EB%B2%95)
    - [참고 블로그 2](https://velog.io/@jmjmjmz732002/Spring-Boot-%EC%84%9C%EB%B2%84%EB%A6%AC%EC%8A%A4-%EA%B8%B0%EB%B0%98-S3-Presigned-URL-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0#accessdenied)
- [x] 의존성 추가
- [x] config 설정 
- [x] 프론트에서 Presigned URL 요청 시 생성하여 반환하기
- [x] 프론트엔드에서 Presigned URL을 사용하여 S3에 이미지를 업로드함 -> 테스트를 통해 확인하였음
- [x] 이때 키값과 presigned url을 OcrData 테이블에 저장해주기 
- [x] S3에서 이미지 URL을 가져와 네이버 클로바 COR API로 요청을 보내기 
- [x] OCR 결과를 프론트에 반환하기 
- [x] 표 추출 기능 사용해보기
- [x] 차트 표도 잘 인식하는지 확인하기

- 참고
    - objectKey는 고유한 값으로 중복하여 사용할 수 없다.
    - jpeg만 가능!!
